export enum BoardPermissions {
  UPDATE_BOARD = "UPDATE_BOARD",
  DELETE_BOARD = "DELETE_BOARD",
  VIEW_BOARD = "VIEW_BOARD",

  ADD_MEMBER_BOARD = "ADD_MEMBER_BOARD",
  REMOVE_MEMBER_BOARD = "REMOVE_MEMBER_BOARD",
  UPDATE_ROLE_MEMBER_BOARD = "UPDATE_ROLE_MEMBER_BOARD",

  CREATE_LIST = "CREATE_LIST",
}
