export enum ProjectPermissions {
  UPDATE_PROJECT = "UPDATE_PROJECT",
  DELETE_PROJECT = "DELETE_PROJECT",
  VIEW_PROJECT = "VIEW_PROJECT",

  ADD_MEMBER_PROJECT = "ADD_MEMBER_PROJECT",
  REMOVE_MEMBER_PROJECT = "REMOVE_MEMBER_PROJECT",
  UPDATE_ROLE_MEMBER_PROJECT = "UPDATE_ROLE_MEMBER_PROJECT",
}
