export enum TaskPermissions {
  UPDATE_TASK = "UPDATE_TASK",
  DELETE_TASK = "DELETE_TASK",
  VIEW_TASK = "VIEW_TASK",

  MOVE_TASK = "MOVE_TASK",
  
  ASSIGN_TASK = "ASSIGN_TASK",
  UNASSIGN_TASK = "UNASSIGN_TASK",

  CREATE_TASK_TAG = "CREATE_TASK_TAG",
  UPDATE_TASK_TAG = "UPDATE_TASK_TAG",
  DELETE_TASK_TAG = "DELETE_TASK_TAG",
  ASSIGN_TASK_TAG = "ASSIGN_TASK_TAG",
  UNASSIGN_TASK_TAG = "UNASSIGN_TASK_TAG",

  CREATE_TASK_COMMENT = "CREATE_TASK_COMMENT",
  DELETE_TASK_COMMENT = "DELETE_TASK_COMMENT",
  UPDATE_TASK_COMMENT = "UPDATE_TASK_COMMENT",
}
